### ISSUE TITLE
netlify config to keep draft posts out of live site

### ISSUE THREAD

**Issue by olets** [hirusi/smix-eleventy-starter#26]
It took me a minute to understand how the env vars were set up, so that I could configure a Netlify build to ignore draft Forestry posts in the production environment. Is supporting that behavior out of the box of interest to you? If so I'll PR the netlify.toml!

**Comment by hirusi** [comment]
Yes -- do you have any thoughts on how stable this configuration would be? It's unlikely I'll maintain it myself but my understanding is that Netlify's API is pretty stable now?

**Comment by olets** [comment]
Can't speak for Netlify but I assume it's stable — if they change it, it'll break things for many people 🙀 

I'll open a PR!
